import React from "react";
import { AbsoluteFill, useCurrentFrame, interpolate, spring, useVideoConfig } from "remotion";
import { BrowserFrame, Caption } from "../components";
import { COLORS } from "../theme";

const Step: React.FC<{ idx: number; title: string; status: "done" | "current" | "next"; delay: number }> = ({ idx, title, status, delay }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const s = spring({ frame: frame - delay, fps, config: { damping: 18, stiffness: 140 } });
  const colorMap = { done: COLORS.accent, current: COLORS.primary, next: COLORS.textDim };
  const c = colorMap[status];
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 16, marginBottom: 12, opacity: s, transform: `translateX(${(1 - s) * 30}px)` }}>
      <div style={{ width: 44, height: 44, borderRadius: 22, background: status === "next" ? "transparent" : c, border: `2px solid ${c}`, display: "flex", alignItems: "center", justifyContent: "center", color: status === "next" ? c : "#fff", fontFamily: "Space Grotesk", fontWeight: 700, boxShadow: status === "current" ? `0 0 24px ${c}` : "none" }}>
        {status === "done" ? "✓" : idx}
      </div>
      <div style={{ flex: 1, padding: 14, background: status === "current" ? `${COLORS.primary}20` : COLORS.card, borderRadius: 10, border: `1px solid ${status === "current" ? COLORS.primary : COLORS.border}` }}>
        <div style={{ fontFamily: "Inter", fontSize: 15, color: COLORS.text, fontWeight: 600 }}>{title}</div>
        <div style={{ fontFamily: "Inter", fontSize: 12, color: COLORS.textDim, marginTop: 3 }}>{status === "done" ? "Completed" : status === "current" ? "In progress" : "Locked"}</div>
      </div>
    </div>
  );
};

export const SceneAIPath: React.FC = () => {
  const frame = useCurrentFrame();
  const titleOp = spring({ frame, fps: 30, config: { damping: 20 } });
  return (
    <AbsoluteFill style={{ alignItems: "center", justifyContent: "center" }}>
      <BrowserFrame url="aiupskillhub.com/my-ai-path">
        <div style={{ padding: 40, height: "100%", overflow: "hidden" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 6, opacity: titleOp }}>
            <div style={{ width: 44, height: 44, borderRadius: 12, background: `linear-gradient(135deg, ${COLORS.primary}, ${COLORS.primaryGlow})`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22, boxShadow: `0 0 30px ${COLORS.primary}` }}>🧠</div>
            <div style={{ fontFamily: "Space Grotesk", fontSize: 30, fontWeight: 700, color: COLORS.text }}>My AI Learning Path</div>
          </div>
          <div style={{ fontFamily: "Inter", fontSize: 14, color: COLORS.textDim, marginBottom: 24, marginLeft: 58 }}>Generated by Aira based on your diagnostic results</div>
          <div style={{ maxWidth: 720 }}>
            <Step idx={1} title="Foundations of AI" status="done" delay={15} />
            <Step idx={2} title="Prompt Engineering" status="done" delay={25} />
            <Step idx={3} title="LLMs in Practice" status="current" delay={35} />
            <Step idx={4} title="AI Agents & Tools" status="next" delay={45} />
            <Step idx={5} title="Capstone Project" status="next" delay={55} />
          </div>
        </div>
      </BrowserFrame>
      <Caption text="AI-personalized learning path" sub="Recommended modules tailored to you" />
    </AbsoluteFill>
  );
};
