import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAllCandidatePaths } from "@/hooks/useCandidateLearningPath";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sparkles, Wand2, RefreshCw, Trash2, User, Brain } from "lucide-react";
import { toast } from "sonner";

const AICandidatePathsManager = () => {
  const { paths, loading, refetch } = useAllCandidatePaths();
  const [candidates, setCandidates] = useState<{ id: string; name: string; email: string }[]>([]);
  const [pickerOpen, setPickerOpen] = useState(false);
  const [selectedCandidateId, setSelectedCandidateId] = useState("");
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    supabase.from("students").select("id, name, email").order("name").then(({ data }) => {
      setCandidates((data as any[]) || []);
    });
  }, []);

  const generateForCandidate = async (candidateId: string) => {
    setGenerating(true);
    try {
      const url = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/generate-candidate-path`;
      const resp = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
        },
        body: JSON.stringify({ candidateId }),
      });
      const json = await resp.json();
      if (!resp.ok) throw new Error(json.error || "Failed");
      toast.success(json.beginnerDefault ? "Beginner path created" : "AI path generated");
      setPickerOpen(false);
      setSelectedCandidateId("");
      refetch();
    } catch (e: any) {
      toast.error(e.message || "Generation failed");
    } finally {
      setGenerating(false);
    }
  };

  const deletePath = async (id: string) => {
    await (supabase.from("candidate_learning_paths") as any).delete().eq("id", id);
    toast.success("Path deleted");
    refetch();
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div>
          <h3 className="font-display font-semibold text-foreground flex items-center gap-2">
            <Brain className="h-5 w-5 text-primary" /> AI-Generated Candidate Paths
          </h3>
          <p className="text-xs text-muted-foreground">
            Adaptive paths generated by AI based on each candidate's progress, scores, and coding activity.
          </p>
        </div>
        <Button onClick={() => setPickerOpen(true)} className="gap-2">
          <Wand2 className="h-4 w-4" /> Generate for Candidate
        </Button>
      </div>

      {loading ? (
        <div className="space-y-3 animate-pulse">
          {[1, 2].map((i) => <div key={i} className="h-24 bg-muted rounded-lg" />)}
        </div>
      ) : paths.length === 0 ? (
        <Card>
          <CardContent className="py-10 text-center text-muted-foreground">
            <Sparkles className="h-10 w-10 mx-auto mb-2 opacity-40" />
            <p className="text-sm">No AI-generated paths yet. Pick a candidate to start.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-3">
          {paths.map((p) => (
            <Card key={p.id} className="border-border">
              <CardContent className="p-4">
                <div className="flex items-start justify-between gap-3 mb-2">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <User className="h-4 w-4 text-muted-foreground" />
                      <span className="font-medium text-foreground text-sm">{p.candidate_name}</span>
                      {p.is_beginner_default ? (
                        <Badge variant="outline" className="text-xs">Beginner Default</Badge>
                      ) : (
                        <Badge className="text-xs gap-1"><Sparkles className="h-3 w-3" /> AI</Badge>
                      )}
                      <span className="text-xs text-muted-foreground">{new Date(p.generated_at).toLocaleDateString()}</span>
                    </div>
                    <div className="font-display font-semibold text-card-foreground text-sm mt-1">{p.title}</div>
                    {p.rationale && (
                      <p className="text-xs text-muted-foreground mt-1 line-clamp-2">{p.rationale}</p>
                    )}
                  </div>
                  <div className="flex gap-1 shrink-0">
                    <Button size="sm" variant="ghost" onClick={() => generateForCandidate(p.candidate_id)} disabled={generating} title="Regenerate">
                      <RefreshCw className={`h-4 w-4 ${generating ? "animate-spin" : ""}`} />
                    </Button>
                    <Button size="sm" variant="ghost" className="text-destructive" onClick={() => deletePath(p.id)}>
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
                <div className="flex flex-wrap gap-1.5 mt-2">
                  {p.modules.map((m, i) => (
                    <Badge key={m.id} variant="outline" className="text-xs">
                      {i + 1}. {m.module_title}
                    </Badge>
                  ))}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <Dialog open={pickerOpen} onOpenChange={setPickerOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Wand2 className="h-5 w-5 text-primary" /> Generate AI Path for Candidate
            </DialogTitle>
          </DialogHeader>
          <div className="py-2">
            <p className="text-sm text-muted-foreground mb-3">
              Select a candidate. The AI will analyze their progress, quizzes, assessments, and coding activity, then build an adaptive learning path.
            </p>
            <Select value={selectedCandidateId} onValueChange={setSelectedCandidateId}>
              <SelectTrigger><SelectValue placeholder="Select candidate" /></SelectTrigger>
              <SelectContent>
                {candidates.map((c) => (
                  <SelectItem key={c.id} value={c.id}>{c.name} — {c.email}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setPickerOpen(false)}>Cancel</Button>
            <Button
              onClick={() => generateForCandidate(selectedCandidateId)}
              disabled={!selectedCandidateId || generating}
              className="gap-2"
            >
              {generating ? <RefreshCw className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
              {generating ? "Generating…" : "Generate Path"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default AICandidatePathsManager;
